// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymizmiocriqdihziaahj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltaXptaW9jcmlxZGloemlhYWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDUyMDIsImV4cCI6MjA2NTIyMTIwMn0.JEU0R3hi-DEP3qlvbQmIHkIkBD_OfMPeFrbGRkdkf-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);